### PR TITLE
Only fetch 1 revision from git during Travis builds.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/tokstyle/8)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tokstyle/8)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tokstyle/8#-:-K_M8W69e_fGXTMKm2jl:bnfp4nl)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tokstyle/8)*

**Comment by abueide** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tokstyle/8#-:-K_NI5XHthNLFpFt5b31:b-jbsf8z)*

**Comment by abueide** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tokstyle/8)*

**Pull request merged**
